# frozen_string_literal: true

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

source "https://rubygems.org"

gem "overcommit"
gem "panolint", github: "panorama-ed/panolint", branch: "main"
